name: 🍎 macOS

# TODO: upload *.dylib / *.framework as artifacts

on:
  push:
    paths:
      - "doc/cpp-demo/**"
    branches-ignore:
      - godot3
  pull_request:
    paths:
      - "doc/cpp-demo/**"
    branches-ignore:
      - godot3

env:
  VCPKG_ROOT: "${{ github.workspace }}/vcpkg"
  VCPKG_DISABLE_METRICS: 1
  vcpkg_tag: "2022.11.14"
  source: "${{ github.workspace }}/doc/cpp-demo"
  build: "${{ github.workspace }}/doc/cpp-demo/build.debug"
  preset: debug
  config: Debug

jobs:
  analyze:
    name: Build
    runs-on: macos-latest

    steps:
      - name: macOS deps
        run: |
          brew install ninja

      - uses: actions/checkout@v3

      - name: Get vcpkg
        run: |
          git clone -n https://github.com/microsoft/vcpkg
          cd vcpkg
          git checkout ${{ env.vcpkg_tag }}
          ./bootstrap-vcpkg.sh

      - name: CMake Configure
        run: cmake --preset ${{ env.preset }} ${{ env.source }}

      - name: CMake Build
        run: cmake --build ${{ env.build }} --config ${{ env.config }} --target install

      - name: CMake Test
        working-directory: ${{ env.build }}
        run: ctest -C ${{env.config}}
